### ISSUE TITLE
DWT and IWT

### ISSUE THREAD

**Issue by Mdahao** [VinAIResearch/WaveDiff#4]
Hi sir，Thanks for your work. What is the difference between the DWT and IWT in WaveCNet and pytorch_wavelets? Which package you are using?

**Comment by hao-pt** [comment]
I apologize for the confusion earlier. Initially, during our research, we used the wavelet transformation from pytorch_wavelets to transform the input image into wavelet subbands. However, we found that this operation is not supported for gradient propagation. Therefore, when designing the Wavelet-embedded generator, we opted to use the wavelet transformations from WaveCNet instead.

In details, most of our experiments utilized wavelet transformations from pytorch_wavelets to process input images, while the wavelet-embedded generator used the ones from WaveCNet. However, only two experiments, namely CelebA 256 & 1024, used wavelet layers from WaveCNet for both the input image and the network.
