### ISSUE TITLE
Inverse a image to latent space and recover it

### ISSUE THREAD

**Issue by Aravinda27** [VinAIResearch/WaveDiff#5]
How to

1) inverse a image to latent space and record the latent.

2) and then reconstruction latent vector to a same image.

anyone can help me, how can i do this.

Thanks.

Best wishes.

**Comment by hao-pt** [comment]
Hi, we have not tried this before but you could refer to [CycleDiffusion](https://arxiv.org/abs/2210.05559) paper that introduces an invertible DPM-Encoder to map an image into latent space using the formulas of reverse process (see 3.2 and A.4). This guarantees the perfect reconstruction.

**Comment by Aravinda27** [comment]
Thanks a lot for the answer..
I am closing the issue...
