### ISSUE TITLE
The result contains serious noise

### ISSUE THREAD

**Issue by LiuYueXian123** [VinAIResearch/WaveDiff#6]
I tried to reproduce the effect in the paper, I did not change any parameters, but the result contains serious noise. Does anyone reproduce the effect cleanly, or what can I do to improve it.

**Comment by hao-pt** [comment]
Could you please give us the details of your test script? What model you are using? (our pretrained models or your reproduced ones)

**Comment by hao-pt** [comment]
Without modifying any hyper-params, here are the results of our sample images. As shown, there are no noise artifacts as you encounter. I decide to close this issue as it is inactive for a while. Feel free to reopen in case you need further support. Cheer!

![samples_cifar10](https://github.com/VinAIResearch/WaveDiff/assets/31931630/797a5529-3e81-48ff-82ae-4842063ffaac)
![samples_celeba_256](https://github.com/VinAIResearch/WaveDiff/assets/31931630/62881915-38df-4288-bc71-8b0961ab4dc8)
