### ISSUE TITLE
Link to the high resolution dataset is broken

### ISSUE THREAD

**Issue by Amarkr1** [VinAIResearch/WaveDiff#8]
Hi,
Can you please update the link for: data512x512.zip and data1024x1024.zip, seems like they are broken

**Comment by hao-pt** [comment]
Thank you for your update! We have uploaded our processed lmdb file at [here](https://drive.google.com/drive/folders/1d_8dhc3HFsSYTvQNN7vbDv5D_lRGHm4g?usp=sharing) for your convenience.
