### ISSUE TITLE
Running celeba_256 data on multiple gpus throws an error

### ISSUE THREAD

**Issue by Amarkr1** [VinAIResearch/WaveDiff#9]
Hi,
When I try to run the celeba_256 on 2 GPUs, I get the following error:
```
Node rank 0, local proc 0, global proc 0
Node rank 0, local proc 1, global proc 1
terminate called after throwing an instance of 'std::system_error'
  what():  Connection refused
```
However, the same code works on a single GPU. Additionally for the menthod mentioned in the paper, dataset celeba_256 can be trained using 1 GPU for wddggan but for ddgan the same runs out of memory. Can you please provide any details how this is executed across multiple GPUs.

Thanks.

**Comment by hao-pt** [comment]
Hi, we observe no error in multi-gpus training (shown in the figure below). For DDGAN training, you should lower the batch size to 4 times as this model directly performs on the original dimensions of input images (e.g. 256x256). Unlike us, our model training is processed on a compact representation of wavelet subbands with a 4x reduction of spatial dimension (e.g. 128x128) so our method can use a larger batch size than the former.
<img width="1506" alt="image" src="https://github.com/VinAIResearch/WaveDiff/assets/31931630/12e74e6f-ec92-4293-a5a9-b81857cad5ed">
